package view;

import javax.swing.*;

public class GUI extends JFrame{
    public JPanel mainWindow;
    public JPanel coreItemsPanel;
    public JPanel kokiriSwordPanel;
    public JPanel masterSwordPanel;
    public JPanel brknBiggoronSwordPanel;
    public JPanel biggoronSwordPanel;
    public JPanel kokiriShieldPanel;
    public JPanel hylianShieldPanel;
    public JPanel mirrorShieldPanel;
    public JPanel goronTunicPanel;
    public JPanel zoraTunicPanel;
    public JPanel ironBootsPanel;
    public JPanel hoverBootsPanel;
    public JLabel kokiriSwordPic;
    public JLabel masterSwordPic;
    public JLabel brknBiggoronSwordPic;
    public JLabel biggoronSwordPic;
    public JLabel kokiriShieldPic;
    public JLabel hylianShieldPic;
    public JLabel mirrorShieldPic;
    public JPanel kokiriTunicPanel;
    public JLabel kokiriTunicPic;
    public JLabel goronTunicPic;
    public JLabel zoraTunicPic;
    public JPanel kokiriBootsPanel;
    public JLabel kokiriBootsPic;
    public JLabel ironBootsPic;
    public JLabel hoverBootsPic;
    public JPanel bulletBagPanel;
    public JLabel bulletBagPic;
    public JPanel bigBulletBagPanel;
    public JLabel bigBulletBagPic;
    public JPanel biggestBulletBagPanel;
    public JLabel biggestBulletBagPic;
    public JPanel silverGauntletPanel;
    public JLabel silverGauntletPic;
    public JPanel goldenGauntletPanel;
    public JLabel goldenGauntletsPic;
    public JPanel dinsFirePanel;
    public JLabel dinsFirePic;
    public JPanel adultsWalletPanel;
    public JLabel adultPanelPic;
    public JPanel giantWalletPanel;
    public JPanel upgradedHeartPanel;
    public JLabel updatesHeartPic;
    public JPanel empty1_2;
    public JPanel quiverPanel;
    public JLabel quiverPic;
    public JPanel bigQuiverPanel;
    public JLabel bigQuiverPic;
    public JPanel biggestQuiverPanel;
    public JLabel biggestQuiverPic;
    public JPanel silverScalePanel;
    public JLabel silverScalePic;
    public JPanel goldenScalePanel;
    public JLabel goldenScalePic;
    public JPanel faroresWindPanel;
    public JLabel faroresWindPic;
    public JPanel stoneOfAgonyPanel;
    public JLabel stoneOfAgonyPic;
    public JPanel gerudoTokenPanel;
    public JLabel gerudoTokenPic;
    public JPanel spinAttackPanel;
    public JLabel spinAttackPic;
    public JPanel empty1_3;
    public JPanel bombBagPanel;
    public JLabel bombBagPic;
    public JPanel bigBombBagPanel;
    public JLabel bigBombBagPic;
    public JPanel biggestBombBagPanel;
    public JLabel biggestBombBagPic;
    public JPanel goronBraceletPanel;
    public JLabel goronBraceletPic;
    public JPanel empty10_3;
    public JPanel nayrusLovePanel;
    public JLabel nayrusLovePic;
    public JPanel magicMeterPanel;
    public JLabel magicMeterPic;
    public JPanel biggerMagicMeterPanel;
    public JLabel biggerMagicMeterPic;
    public JPanel empty14_3;


    public void setGUI() {
        setContentPane(mainWindow);
        setSize(600, 1000);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        mainWindow.add(coreItemsPanel);
        setVisible(true);
    }
}
